import noclose
add = True
while add:
    item = input("What item would you like to add to your shopping list?\n")
    q = input("How much?\n")
    f = open("shoppinglist.txt", "a")
    f.write("\n Item: ", item, " quantity: ", q)
    f.close()
    print("Item('s) have been added to your shopping list. \nYou can view the items in your shopping list by openning the \"shoppinglist.txt\" file generated by this app.")
    more = input("Would you like to add another item to your shopping list? (y/n)\n")
    
    if more == "n" or more == "N":
        print("OK, bye!")
        noclose
        exit()
        add = False

print("Error invalid input")
noclose
exit()
